# Generated by Django 2.1.5 on 2019-02-23 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('Event_id', models.IntegerField()),
                ('Event_name', models.CharField(max_length=48)),
                ('Event_time', models.DateTimeField()),
                ('Event_venue', models.CharField(max_length=100)),
                ('Max_players', models.IntegerField()),
                ('Players_registratered', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_sports_app.Event')),
            ],
            options={
                'verbose_name_plural': 'participants',
            },
        ),
    ]
