# Generated by Django 2.1.5 on 2019-02-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_sports_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Event_id',
        ),
    ]
