# Generated by Django 2.1.3 on 2019-03-08 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_sports_app', '0002_remove_event_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='text',
        ),
        migrations.AddField(
            model_name='participant',
            name='participant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
