# Generated by Django 2.1.3 on 2019-03-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_sports_app', '0003_auto_20190308_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='participant',
            new_name='owner',
        ),
    ]
