# Generated by Django 2.1.3 on 2019-03-08 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_sports_app', '0004_auto_20190308_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='owner',
            new_name='participant',
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
