# Generated by Django 2.1.5 on 2019-03-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_sports_app', '0005_auto_20190308_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='event',
            new_name='eventID',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='participant',
            new_name='participantID',
        ),
    ]
