# Generated by Django 2.1.5 on 2019-04-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_sports_app', '0007_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='address',
        ),
        migrations.AddField(
            model_name='profiles',
            name='email',
            field=models.EmailField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Players_registratered',
            field=models.IntegerField(default=1),
        ),
    ]
