# Generated by Django 2.1.5 on 2019-04-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_sports_app', '0008_auto_20190422_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isNotify',
            field=models.BooleanField(default=False),
        ),
    ]
